/*
ESTE CÓDIGO IMPLEMENTA UMA VERSÃO SIMPLES 
DE SOFTWARE PARA UM ROBÔ CUJA MISSÃO É "FUGIR DA LUZ".
NATURALMENTE O ROBÔ PERMANECE "ESTACIONADO", 
MAS, AO SER ILUMINADO COM A LANTERNA DE UM SMARTPHONE (POR EXEMPLO),
ATIVA OS MOTORES PARA FUGIR DA FONTE DE LUZ.
O CÓDIGO FOI PRODUZIDO DURANTE AULA DE 
"INTRODUÇÃO À ROBÓTICA COM ARDUINO" NO FAB LAB CEU HELIÓPOLIS.
*/

//INÍCIO DO CÓDIGO
#include <AFMotor.h> //ADICIONA A BIBLIOTECA AFMOTOR. DOWNLOAD EM: https://github.com/adafruit/

int valorLDR; //CRIA UMA VARIÁVEL PARA ARMAZENAR OS DADOS LIDOS PELO LDR

AF_DCMotor motor_d(4); //MOTOR DC NA LIGAÇÃO M4 DO SHIELD
AF_DCMotor motor_e(3); //MOTOR DC NA LIGAÇÃO M3 DO SHIELD

void setup() {
  pinMode(A5, INPUT); //PINO RESPONSÁVEL PELA LEITURA DO LDR
  //Serial.begin(9600);
}

void loop() {

  //ARMAZENA O VALOR LIDO PELO LDR
  valorLDR = analogRead(A5);

  //VERIFICA O VALOR LIDO PELO LDR. O VALOR 550 FOI ESTABELECIDO DE ACORDO COM AS CONDIÇÕES DE ILUMINAÇÃO DO DIA E DO LOCAL ONDE O ROBÔ FOI MONTADO. 
  //É IMPORTANTE QUE SEJA MELHOR CALIBRADO.
  while(valorLDR >= 550) {

    //ROTACIONA O ROBÔ
    motor_d.setSpeed(255);
    motor_e.setSpeed(255);
    motor_d.run(FORWARD);
    motor_e.run(BACKWARD);

    delay(500);

    //DESLOCA O ROBÔ PARA FRENTE
    motor_d.run(FORWARD);
    motor_e.run(FORWARD);

    delay(1000);

    //ARMAZENA NOVAMENTE O VALOR DO LDR PARA VERIFICAR SE A CONDIÇÃO DO LOOP FOI ATENDIDA
    valorLDR = analogRead(A5);
  }
  
  //DESLIGA OS MOTOROES E "ESTACIONA" O ROBÔ
  motor_d.setSpeed(0);
  motor_e.setSpeed(0);
  motor_e.run(RELEASE);
  motor_d.run(RELEASE);
  
}
